#!/bin/sh

# skip if we are preserving the configuration during a sysupgrade
[ -e '/sysupgrade.tgz' ] && exit 0

uci set system.@system[0].hostname="opi-gateway"
uci set system.@system[0].timezone="CET-1CEST,M3.5.0,M10.5.0/3"

uci set network.lan.ipaddr="192.168.5.1"

uci set dropbear.@dropbear[0].PasswordAuth=off
uci set dropbear.@dropbear[0].RootPasswordAuth=off

uci add firewall rule
  uci set firewall.@rule[-1].name='Allow-SSH'
  uci set firewall.@rule[-1].src=wan
  uci set firewall.@rule[-1].target=ACCEPT
  uci set firewall.@rule[-1].proto=tcp
  uci set firewall.@rule[-1].dest_port=2242

uci set network.wwan="interface"
  uci set network.wwan.proto='dhcp'
  uci set network.wwan.ifname='eth2'  

uci set dhcp.wwan=dhcp
  uci set dhcp.wwan.interface='wwan'
  uci set dhcp.wwan.ignore='1'

uci add_list firewall.@zone[1].network='wwan'

uci commit

cat <<iEOF >> /etc/hosts
192.168.5.1 gateway.mgorski.eu

iEOF

cat >> /etc/sysupgrade.conf <<EOF
/root
/service
/etc/init.d/runsvdir-init.d

EOF

cat >> /etc/timezone <<EOF
Europe/Warsaw

EOF

sync

exit 0
